/**
 * Proyecto Cierzo API
 * Back-end API del Proyecto Cierzo
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The AccountItemUpdate model module.
* @module model/AccountItemUpdate
* @version 1.0.0
*/
export default class AccountItemUpdate {
    /**
    * Constructs a new <code>AccountItemUpdate</code>.
    * @alias module:model/AccountItemUpdate
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>AccountItemUpdate</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/AccountItemUpdate} obj Optional instance to populate.
    * @return {module:model/AccountItemUpdate} The populated <code>AccountItemUpdate</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AccountItemUpdate();

            
            
            

            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('bio')) {
                obj['bio'] = ApiClient.convertToType(data['bio'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} username
    */
    username = undefined;
    /**
    * @member {String} name
    */
    name = undefined;
    /**
    * @member {String} bio
    */
    bio = undefined;








}


