/**
 * Proyecto Cierzo API
 * Back-end API del Proyecto Cierzo
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The AlbumItemNew model module.
* @module model/AlbumItemNew
* @version 1.0.0
*/
export default class AlbumItemNew {
    /**
    * Constructs a new <code>AlbumItemNew</code>.
    * @alias module:model/AlbumItemNew
    * @class
    * @param name {String} 
    * @param authorID {String} 
    * @param publishDate {Date} 
    */

    constructor(name, authorID, publishDate) {
        

        
        

        this['name'] = name;this['authorID'] = authorID;this['publishDate'] = publishDate;

        
    }

    /**
    * Constructs a <code>AlbumItemNew</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/AlbumItemNew} obj Optional instance to populate.
    * @return {module:model/AlbumItemNew} The populated <code>AlbumItemNew</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AlbumItemNew();

            
            
            

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('authorID')) {
                obj['authorID'] = ApiClient.convertToType(data['authorID'], 'String');
            }
            if (data.hasOwnProperty('publishDate')) {
                obj['publishDate'] = ApiClient.convertToType(data['publishDate'], 'Date');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} name
    */
    name = undefined;
    /**
    * @member {String} authorID
    */
    authorID = undefined;
    /**
    * @member {Date} publishDate
    */
    publishDate = undefined;
    /**
    * @member {String} description
    */
    description = undefined;








}


