/**
 * Proyecto Cierzo API
 * Back-end API del Proyecto Cierzo
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import SongItem from './SongItem';





/**
* The AlbumItem model module.
* @module model/AlbumItem
* @version 1.0.0
*/
export default class AlbumItem {
    /**
    * Constructs a new <code>AlbumItem</code>.
    * @alias module:model/AlbumItem
    * @class
    * @param id {String} 
    * @param name {String} 
    * @param authorID {String} 
    * @param authorName {String} 
    * @param description {String} 
    * @param songs {Array.<module:model/SongItem>} 
    */

    constructor(id, name, authorID, authorName, description, songs) {
        

        
        

        this['id'] = id;this['name'] = name;this['authorID'] = authorID;this['authorName'] = authorName;this['description'] = description;this['songs'] = songs;

        
    }

    /**
    * Constructs a <code>AlbumItem</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/AlbumItem} obj Optional instance to populate.
    * @return {module:model/AlbumItem} The populated <code>AlbumItem</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AlbumItem();

            
            
            

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('authorID')) {
                obj['authorID'] = ApiClient.convertToType(data['authorID'], 'String');
            }
            if (data.hasOwnProperty('authorName')) {
                obj['authorName'] = ApiClient.convertToType(data['authorName'], 'String');
            }
            if (data.hasOwnProperty('publishDate')) {
                obj['publishDate'] = ApiClient.convertToType(data['publishDate'], 'Date');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('songs')) {
                obj['songs'] = ApiClient.convertToType(data['songs'], [SongItem]);
            }
        }
        return obj;
    }

    /**
    * @member {String} id
    */
    id = undefined;
    /**
    * @member {String} name
    */
    name = undefined;
    /**
    * @member {String} authorID
    */
    authorID = undefined;
    /**
    * @member {String} authorName
    */
    authorName = undefined;
    /**
    * @member {Date} publishDate
    */
    publishDate = undefined;
    /**
    * @member {String} description
    */
    description = undefined;
    /**
    * @member {Array.<module:model/SongItem>} songs
    */
    songs = undefined;








}


