/**
 * Proyecto Cierzo API
 * Back-end API del Proyecto Cierzo
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import AlbumItem from './AlbumItem';





/**
* The AuthorItem model module.
* @module model/AuthorItem
* @version 1.0.0
*/
export default class AuthorItem {
    /**
    * Constructs a new <code>AuthorItem</code>.
    * @alias module:model/AuthorItem
    * @class
    * @param id {String} 
    * @param name {String} 
    * @param bio {String} 
    * @param albums {Array.<module:model/AlbumItem>} 
    */

    constructor(id, name, bio, albums) {
        

        
        

        this['id'] = id;this['name'] = name;this['bio'] = bio;this['albums'] = albums;

        
    }

    /**
    * Constructs a <code>AuthorItem</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/AuthorItem} obj Optional instance to populate.
    * @return {module:model/AuthorItem} The populated <code>AuthorItem</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AuthorItem();

            
            
            

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('bio')) {
                obj['bio'] = ApiClient.convertToType(data['bio'], 'String');
            }
            if (data.hasOwnProperty('albums')) {
                obj['albums'] = ApiClient.convertToType(data['albums'], [AlbumItem]);
            }
        }
        return obj;
    }

    /**
    * @member {String} id
    */
    id = undefined;
    /**
    * @member {String} name
    */
    name = undefined;
    /**
    * @member {String} bio
    */
    bio = undefined;
    /**
    * @member {Array.<module:model/AlbumItem>} albums
    */
    albums = undefined;








}


