/**
 * Proyecto Cierzo API
 * Back-end API del Proyecto Cierzo
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The AuthorItemNew model module.
* @module model/AuthorItemNew
* @version 1.0.0
*/
export default class AuthorItemNew {
    /**
    * Constructs a new <code>AuthorItemNew</code>.
    * @alias module:model/AuthorItemNew
    * @class
    * @param name {String} 
    * @param bio {String} 
    */

    constructor(name, bio) {
        

        
        

        this['name'] = name;this['bio'] = bio;

        
    }

    /**
    * Constructs a <code>AuthorItemNew</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/AuthorItemNew} obj Optional instance to populate.
    * @return {module:model/AuthorItemNew} The populated <code>AuthorItemNew</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AuthorItemNew();

            
            
            

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('bio')) {
                obj['bio'] = ApiClient.convertToType(data['bio'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} name
    */
    name = undefined;
    /**
    * @member {String} bio
    */
    bio = undefined;








}


