/**
 * Proyecto Cierzo API
 * Back-end API del Proyecto Cierzo
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import SongItem from './SongItem';





/**
* The PlaylistItem model module.
* @module model/PlaylistItem
* @version 1.0.0
*/
export default class PlaylistItem {
    /**
    * Constructs a new <code>PlaylistItem</code>.
    * @alias module:model/PlaylistItem
    * @class
    * @param id {String} 
    * @param name {String} 
    * @param ownerID {String} 
    * @param ownerName {String} 
    * @param creationDate {Date} 
    * @param description {String} 
    * @param songs {Array.<module:model/SongItem>} 
    */

    constructor(id, name, ownerID, ownerName, creationDate, description, songs) {
        

        
        

        this['id'] = id;this['name'] = name;this['ownerID'] = ownerID;this['ownerName'] = ownerName;this['creationDate'] = creationDate;this['description'] = description;this['songs'] = songs;

        
    }

    /**
    * Constructs a <code>PlaylistItem</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/PlaylistItem} obj Optional instance to populate.
    * @return {module:model/PlaylistItem} The populated <code>PlaylistItem</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PlaylistItem();

            
            
            

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('ownerID')) {
                obj['ownerID'] = ApiClient.convertToType(data['ownerID'], 'String');
            }
            if (data.hasOwnProperty('ownerName')) {
                obj['ownerName'] = ApiClient.convertToType(data['ownerName'], 'String');
            }
            if (data.hasOwnProperty('creationDate')) {
                obj['creationDate'] = ApiClient.convertToType(data['creationDate'], 'Date');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('songs')) {
                obj['songs'] = ApiClient.convertToType(data['songs'], [SongItem]);
            }
        }
        return obj;
    }

    /**
    * @member {String} id
    */
    id = undefined;
    /**
    * @member {String} name
    */
    name = undefined;
    /**
    * @member {String} ownerID
    */
    ownerID = undefined;
    /**
    * @member {String} ownerName
    */
    ownerName = undefined;
    /**
    * @member {Date} creationDate
    */
    creationDate = undefined;
    /**
    * @member {String} description
    */
    description = undefined;
    /**
    * @member {Array.<module:model/SongItem>} songs
    */
    songs = undefined;








}


