/**
 * Proyecto Cierzo API
 * Back-end API del Proyecto Cierzo
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The PlaylistItemNew model module.
* @module model/PlaylistItemNew
* @version 1.0.0
*/
export default class PlaylistItemNew {
    /**
    * Constructs a new <code>PlaylistItemNew</code>.
    * @alias module:model/PlaylistItemNew
    * @class
    * @param name {String} 
    */

    constructor(name) {
        

        
        

        this['name'] = name;

        
    }

    /**
    * Constructs a <code>PlaylistItemNew</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/PlaylistItemNew} obj Optional instance to populate.
    * @return {module:model/PlaylistItemNew} The populated <code>PlaylistItemNew</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PlaylistItemNew();

            
            
            

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} name
    */
    name = undefined;
    /**
    * @member {String} description
    */
    description = undefined;








}


