/**
 * Proyecto Cierzo API
 * Back-end API del Proyecto Cierzo
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import ProfileItem from './ProfileItem';





/**
* The ProfileItem model module.
* @module model/ProfileItem
* @version 1.0.0
*/
export default class ProfileItem {
    /**
    * Constructs a new <code>ProfileItem</code>.
    * @alias module:model/ProfileItem
    * @class
    * @param id {String} 
    * @param username {String} 
    * @param name {String} 
    * @param bio {String} 
    * @param friends {Array.<module:model/ProfileItem>} 
    */

    constructor(id, username, name, bio, friends) {
        

        
        

        this['id'] = id;this['username'] = username;this['name'] = name;this['bio'] = bio;this['friends'] = friends;

        
    }

    /**
    * Constructs a <code>ProfileItem</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ProfileItem} obj Optional instance to populate.
    * @return {module:model/ProfileItem} The populated <code>ProfileItem</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProfileItem();

            
            
            

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('bio')) {
                obj['bio'] = ApiClient.convertToType(data['bio'], 'String');
            }
            if (data.hasOwnProperty('friends')) {
                obj['friends'] = ApiClient.convertToType(data['friends'], [ProfileItem]);
            }
        }
        return obj;
    }

    /**
    * @member {String} id
    */
    id = undefined;
    /**
    * @member {String} username
    */
    username = undefined;
    /**
    * @member {String} name
    */
    name = undefined;
    /**
    * @member {String} bio
    */
    bio = undefined;
    /**
    * @member {Array.<module:model/ProfileItem>} friends
    */
    friends = undefined;








}


