/**
 * Proyecto Cierzo API
 * Back-end API del Proyecto Cierzo
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The SessionItem model module.
* @module model/SessionItem
* @version 1.0.0
*/
export default class SessionItem {
    /**
    * Constructs a new <code>SessionItem</code>.
    * @alias module:model/SessionItem
    * @class
    * @param playlistID {String} 
    * @param songID {String} 
    * @param second {String} 
    */

    constructor(playlistID, songID, second) {
        

        
        

        this['playlistID'] = playlistID;this['songID'] = songID;this['second'] = second;

        
    }

    /**
    * Constructs a <code>SessionItem</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/SessionItem} obj Optional instance to populate.
    * @return {module:model/SessionItem} The populated <code>SessionItem</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SessionItem();

            
            
            

            if (data.hasOwnProperty('playlistID')) {
                obj['playlistID'] = ApiClient.convertToType(data['playlistID'], 'String');
            }
            if (data.hasOwnProperty('songID')) {
                obj['songID'] = ApiClient.convertToType(data['songID'], 'String');
            }
            if (data.hasOwnProperty('second')) {
                obj['second'] = ApiClient.convertToType(data['second'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} playlistID
    */
    playlistID = undefined;
    /**
    * @member {String} songID
    */
    songID = undefined;
    /**
    * @member {String} second
    */
    second = undefined;








}


