/**
 * Proyecto Cierzo API
 * Back-end API del Proyecto Cierzo
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The SongItemNew model module.
* @module model/SongItemNew
* @version 1.0.0
*/
export default class SongItemNew {
    /**
    * Constructs a new <code>SongItemNew</code>.
    * @alias module:model/SongItemNew
    * @class
    * @param name {String} 
    * @param lenght {String} 
    * @param authorID {String} 
    * @param albumID {String} 
    * @param genre {Array.<String>} 
    */

    constructor(name, lenght, authorID, albumID, genre) {
        

        
        

        this['name'] = name;this['lenght'] = lenght;this['authorID'] = authorID;this['albumID'] = albumID;this['genre'] = genre;

        
    }

    /**
    * Constructs a <code>SongItemNew</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/SongItemNew} obj Optional instance to populate.
    * @return {module:model/SongItemNew} The populated <code>SongItemNew</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SongItemNew();

            
            
            

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('lenght')) {
                obj['lenght'] = ApiClient.convertToType(data['lenght'], 'String');
            }
            if (data.hasOwnProperty('authorID')) {
                obj['authorID'] = ApiClient.convertToType(data['authorID'], 'String');
            }
            if (data.hasOwnProperty('albumID')) {
                obj['albumID'] = ApiClient.convertToType(data['albumID'], 'String');
            }
            if (data.hasOwnProperty('genre')) {
                obj['genre'] = ApiClient.convertToType(data['genre'], ['String']);
            }
        }
        return obj;
    }

    /**
    * @member {String} name
    */
    name = undefined;
    /**
    * @member {String} lenght
    */
    lenght = undefined;
    /**
    * @member {String} authorID
    */
    authorID = undefined;
    /**
    * @member {String} albumID
    */
    albumID = undefined;
    /**
    * @member {Array.<String>} genre
    */
    genre = undefined;








}


