/**
 * Proyecto Cierzo API
 * Back-end API del Proyecto Cierzo
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The SongItem model module.
* @module model/SongItem
* @version 1.0.0
*/
export default class SongItem {
    /**
    * Constructs a new <code>SongItem</code>.
    * @alias module:model/SongItem
    * @class
    * @param id {String} 
    * @param name {String} 
    * @param lenght {String} 
    * @param authorID {String} 
    * @param authorName {String} 
    * @param albumID {String} 
    * @param albumName {String} 
    * @param genre {Array.<String>} 
    */

    constructor(id, name, lenght, authorID, authorName, albumID, albumName, genre) {
        

        
        

        this['id'] = id;this['name'] = name;this['lenght'] = lenght;this['authorID'] = authorID;this['authorName'] = authorName;this['albumID'] = albumID;this['albumName'] = albumName;this['genre'] = genre;

        
    }

    /**
    * Constructs a <code>SongItem</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/SongItem} obj Optional instance to populate.
    * @return {module:model/SongItem} The populated <code>SongItem</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SongItem();

            
            
            

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('lenght')) {
                obj['lenght'] = ApiClient.convertToType(data['lenght'], 'String');
            }
            if (data.hasOwnProperty('authorID')) {
                obj['authorID'] = ApiClient.convertToType(data['authorID'], 'String');
            }
            if (data.hasOwnProperty('authorName')) {
                obj['authorName'] = ApiClient.convertToType(data['authorName'], 'String');
            }
            if (data.hasOwnProperty('albumID')) {
                obj['albumID'] = ApiClient.convertToType(data['albumID'], 'String');
            }
            if (data.hasOwnProperty('albumName')) {
                obj['albumName'] = ApiClient.convertToType(data['albumName'], 'String');
            }
            if (data.hasOwnProperty('genre')) {
                obj['genre'] = ApiClient.convertToType(data['genre'], ['String']);
            }
        }
        return obj;
    }

    /**
    * @member {String} id
    */
    id = undefined;
    /**
    * @member {String} name
    */
    name = undefined;
    /**
    * @member {String} lenght
    */
    lenght = undefined;
    /**
    * @member {String} authorID
    */
    authorID = undefined;
    /**
    * @member {String} authorName
    */
    authorName = undefined;
    /**
    * @member {String} albumID
    */
    albumID = undefined;
    /**
    * @member {String} albumName
    */
    albumName = undefined;
    /**
    * @member {Array.<String>} genre
    */
    genre = undefined;








}


