/**
* Proyecto Cierzo API
* Back-end API del Proyecto Cierzo
*
* OpenAPI spec version: 1.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models

import io.swagger.client.models.ProfileItem

/**
 * 
 * @param id 
 * @param username 
 * @param name 
 * @param bio 
 * @param mail 
 * @param friends 
 */
data class AccountItem (
    val id: kotlin.String,
    val username: kotlin.String,
    val name: kotlin.String,
    val bio: kotlin.String,
    val mail: kotlin.String,
    val friends: kotlin.Array<ProfileItem>
) {

}

