/**
 * Proyecto Cierzo API
 * Back-end API del Proyecto Cierzo
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import AlbumItem from '../model/AlbumItem';

/**
* Admin service.
* @module api/AdminApi
* @version 1.0.0
*/
export default class AdminApi {

    /**
    * Constructs a new AdminApi. 
    * @alias module:api/AdminApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the addAlbumSong operation.
     * @callback module:api/AdminApi~addAlbumSongCallback
     * @param {String} error Error message, if any.
     * @param {module:model/AlbumItem} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * añade una canción a un album
     * Un admin añade una canción a un album
     * @param {String} albumID ID del album
     * @param {Object} opts Optional parameters
     * @param {String} opts.songID Song to add
     * @param {module:api/AdminApi~addAlbumSongCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/AlbumItem}
     */
    addAlbumSong(albumID, opts, callback) {
      opts = opts || {};
      let postBody = opts['songID'];

      // verify the required parameter 'albumID' is set
      if (albumID === undefined || albumID === null) {
        throw new Error("Missing the required parameter 'albumID' when calling addAlbumSong");
      }


      let pathParams = {
        'albumID': albumID
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = AlbumItem;

      return this.apiClient.callApi(
        '/albums/{albumID}/songs', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }


}
