/**
 * Proyecto Cierzo API
 * Back-end API del Proyecto Cierzo
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import AccountItem from './model/AccountItem';
import AccountItemUpdate from './model/AccountItemUpdate';
import AlbumItem from './model/AlbumItem';
import AlbumItemNew from './model/AlbumItemNew';
import AuthorItem from './model/AuthorItem';
import AuthorItemNew from './model/AuthorItemNew';
import LoginItem from './model/LoginItem';
import PlaylistItem from './model/PlaylistItem';
import PlaylistItemNew from './model/PlaylistItemNew';
import ProfileItem from './model/ProfileItem';
import SessionItem from './model/SessionItem';
import SignUpItem from './model/SignUpItem';
import SongItem from './model/SongItem';
import SongItemNew from './model/SongItemNew';
import AdminApi from './api/AdminApi';
import AdminsApi from './api/AdminsApi';
import PublicApi from './api/PublicApi';
import UsersApi from './api/UsersApi';


/**
* Back_end_API_del_Proyecto_Cierzo.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var ProyectoCierzoApi = require('index'); // See note below*.
* var xxxSvc = new ProyectoCierzoApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new ProyectoCierzoApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new ProyectoCierzoApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new ProyectoCierzoApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AccountItem model constructor.
     * @property {module:model/AccountItem}
     */
    AccountItem,

    /**
     * The AccountItemUpdate model constructor.
     * @property {module:model/AccountItemUpdate}
     */
    AccountItemUpdate,

    /**
     * The AlbumItem model constructor.
     * @property {module:model/AlbumItem}
     */
    AlbumItem,

    /**
     * The AlbumItemNew model constructor.
     * @property {module:model/AlbumItemNew}
     */
    AlbumItemNew,

    /**
     * The AuthorItem model constructor.
     * @property {module:model/AuthorItem}
     */
    AuthorItem,

    /**
     * The AuthorItemNew model constructor.
     * @property {module:model/AuthorItemNew}
     */
    AuthorItemNew,

    /**
     * The LoginItem model constructor.
     * @property {module:model/LoginItem}
     */
    LoginItem,

    /**
     * The PlaylistItem model constructor.
     * @property {module:model/PlaylistItem}
     */
    PlaylistItem,

    /**
     * The PlaylistItemNew model constructor.
     * @property {module:model/PlaylistItemNew}
     */
    PlaylistItemNew,

    /**
     * The ProfileItem model constructor.
     * @property {module:model/ProfileItem}
     */
    ProfileItem,

    /**
     * The SessionItem model constructor.
     * @property {module:model/SessionItem}
     */
    SessionItem,

    /**
     * The SignUpItem model constructor.
     * @property {module:model/SignUpItem}
     */
    SignUpItem,

    /**
     * The SongItem model constructor.
     * @property {module:model/SongItem}
     */
    SongItem,

    /**
     * The SongItemNew model constructor.
     * @property {module:model/SongItemNew}
     */
    SongItemNew,

    /**
    * The AdminApi service constructor.
    * @property {module:api/AdminApi}
    */
    AdminApi,

    /**
    * The AdminsApi service constructor.
    * @property {module:api/AdminsApi}
    */
    AdminsApi,

    /**
    * The PublicApi service constructor.
    * @property {module:api/PublicApi}
    */
    PublicApi,

    /**
    * The UsersApi service constructor.
    * @property {module:api/UsersApi}
    */
    UsersApi
};
